"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Plus, Power, Route, WalletCards } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout";
import { BarList, EmptyState, MetricCard, Panel, PanelHeader, StatusBadge } from "@/components/ui/Console";
import { apiFetch } from "@/lib/api-client";

type Usage = {id:string;provider:string;model:string;input_tokens:number;output_tokens:number;cost_usd:number;trace_id?:string;source:string;occurred_at:string};
type Budget = {spent_usd:number;limit_usd:number;warning_ratio:number;hard_limit:boolean;warning:boolean;exceeded:boolean};
type ModelRoute = {id:string;model_alias:string;provider:string;upstream_model:string;base_url:string;api_key_env:string;secret_configured:boolean;priority:number;enabled:boolean;timeout_seconds:number;input_cost_per_million:number;output_cost_per_million:number};
type Tco = {total_usd:number;categories:{category:string;amount_usd:number;minutes:number;events:number}[];recent:any[]};

const initialRoute = {model_alias:"coding-default",provider:"openai",upstream_model:"gpt-4.1-mini",base_url:"https://api.openai.com/v1",api_key_env:"MODEL_PROVIDER_OPENAI_API_KEY",priority:100,enabled:true,timeout_seconds:30,max_retries:1,input_cost_per_million:0,output_cost_per_million:0};

export default function Page(){
  const [rows,setRows]=useState<Usage[]>([]); const [budgets,setBudgets]=useState<Budget[]>([]); const [routes,setRoutes]=useState<ModelRoute[]>([]); const [tco,setTco]=useState<Tco>({total_usd:0,categories:[],recent:[]});
  const [form,setForm]=useState(initialRoute); const [showForm,setShowForm]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const period=new Date().toISOString().slice(0,7);
  async function load(){const[a,b,c,d]=await Promise.all([apiFetch<Usage[]>("/api/governance/usage"),apiFetch<Budget[]>(`/api/budgets?period=${period}`),apiFetch<ModelRoute[]>("/api/model-gateway/routes"),apiFetch<Tco>("/api/model-gateway/cost-events")]);setRows(a.data??[]);setBudgets(b.data??[]);setRoutes(c.data??[]);setTco(d.data??{total_usd:0,categories:[],recent:[]});setError(a.error?.message||b.error?.message||c.error?.message||d.error?.message||"")}
  useEffect(()=>{void load()},[]);
  async function createBudget(){await apiFetch("/api/budgets",{method:"PUT",body:JSON.stringify({scope_type:"workspace",scope_id:"*",period,limit_usd:100,warning_ratio:.8,hard_limit:true})});await load()}
  async function createRoute(event:FormEvent){event.preventDefault();const result=await apiFetch("/api/model-gateway/routes",{method:"POST",body:JSON.stringify(form)});if(result.error){setError(result.error.message);return}setNotice("模型路由已创建；密钥仍由环境变量注入。可为同一别名添加更低优先级的降级路由。");setShowForm(false);await load()}
  async function disableRoute(id:string){if(!confirm("停用此模型路由？已有调用不受影响，新调用会转向下一优先级。"))return;const result=await apiFetch(`/api/model-gateway/routes/${id}`,{method:"DELETE"});if(result.error)setError(result.error.message);else await load()}
  const total=rows.reduce((sum,row)=>sum+row.cost_usd,0);const tokens=rows.reduce((sum,row)=>sum+row.input_tokens+row.output_tokens,0);
  const models=useMemo(()=>{const map:Record<string,{label:string;value:number;cost:number}>={};for(const row of rows){const key=`${row.provider}/${row.model}`;map[key]??={label:key,value:0,cost:0};map[key].value++;map[key].cost+=row.cost_usd}return Object.values(map).sort((a,b)=>b.value-a.value)},[rows]);const budget=budgets[0];
  return <AppLayout title="模型网关与成本" subtitle="统一模型别名、主备路由、硬预算和全口径 TCO；供应商密钥不进入数据库。">
    {error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="模型调用成本" value={`$${total.toFixed(4)}`} description={`${rows.length} 次可归因调用`}/><MetricCard label="全口径 TCO" value={`$${tco.total_usd.toFixed(2)}`} description="模型、人工、返工与事故"/><MetricCard label="本月预算使用" value={budget?`${(budget.spent_usd/budget.limit_usd*100).toFixed(1)}%`:"未配置"} description={budget?`$${budget.spent_usd.toFixed(2)} / $${budget.limit_usd.toFixed(2)}`:"建议设置硬预算"} tone={budget?.exceeded?"red":budget?.warning?"amber":"emerald"}/><MetricCard label="可用路由" value={routes.filter(r=>r.enabled&&r.secret_configured).length} description={`${new Set(routes.map(r=>r.model_alias)).size} 个模型别名`}/></div>
    <Panel className="mt-5"><PanelHeader title="模型路由目录" description="同一别名按优先级故障转移；429、5xx 与超时采用有界重试" action={<button onClick={()=>setShowForm(!showForm)} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3.5 py-2 text-sm text-white"><Plus className="h-4 w-4"/>新增路由</button>}/>
      {showForm&&<form onSubmit={createRoute} className="grid gap-3 border-b border-slate-100 bg-slate-50 p-5 md:grid-cols-2 xl:grid-cols-4">{([['model_alias','模型别名'],['provider','供应商'],['upstream_model','上游模型'],['base_url','Base URL'],['api_key_env','密钥环境变量']] as const).map(([key,label])=><label key={key} className="text-xs text-slate-500">{label}<input value={String(form[key])} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900"/></label>)}<label className="text-xs text-slate-500">优先级<input type="number" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"/></label><label className="text-xs text-slate-500">输入价 / 百万 Token<input type="number" step="0.01" value={form.input_cost_per_million} onChange={e=>setForm({...form,input_cost_per_million:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"/></label><label className="text-xs text-slate-500">输出价 / 百万 Token<input type="number" step="0.01" value={form.output_cost_per_million} onChange={e=>setForm({...form,output_cost_per_million:Number(e.target.value)})} className="mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"/></label><div className="flex items-end"><button className="w-full rounded-lg bg-slate-950 px-4 py-2 text-sm text-white">保存路由</button></div></form>}
      {routes.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">别名 / 上游</th><th className="px-4 py-3">Provider</th><th className="px-4 py-3">优先级</th><th className="px-4 py-3">密钥</th><th className="px-4 py-3">超时</th><th className="px-4 py-3">操作</th></tr></thead><tbody>{routes.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-5 py-4"><div className="font-medium">{r.model_alias}</div><div className="mt-1 text-xs text-slate-400">{r.upstream_model}</div></td><td className="px-4 py-4">{r.provider}</td><td className="px-4 py-4"><span className="inline-flex items-center gap-1"><Route className="h-3.5 w-3.5"/>{r.priority}</span></td><td className="px-4 py-4"><StatusBadge value={r.secret_configured?"active":"pending"}/><div className="mt-1 font-mono text-[10px] text-slate-400">{r.api_key_env}</div></td><td className="px-4 py-4">{r.timeout_seconds}s</td><td className="px-4 py-4"><button onClick={()=>disableRoute(r.id)} disabled={!r.enabled} className="inline-flex items-center gap-1 text-xs text-red-600 disabled:text-slate-300"><Power className="h-3.5 w-3.5"/>停用</button></td></tr>)}</tbody></table></div>:<EmptyState title="尚未配置统一模型路由" description="先创建主路由，再用相同别名创建低优先级降级路由。"/>}
    </Panel>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Panel><PanelHeader title="TCO 构成" description="避免只计算 Token，漏掉审批、返工和事故成本"/><div className="p-5">{tco.categories.length?<BarList items={tco.categories.map(item=>({label:item.category,value:item.amount_usd,display:`$${item.amount_usd.toFixed(2)} · ${item.minutes.toFixed(0)} 分钟`}))}/>:<EmptyState title="暂无 TCO 事件" description="模型调用会自动记账；人工、返工和事故成本可通过 API/工单上报。"/>}</div></Panel><Panel><PanelHeader title="预算与硬门禁" description="硬预算在请求上游模型之前执行" action={!budget?<button onClick={createBudget} className="rounded-lg bg-slate-950 px-3.5 py-2 text-sm text-white">创建 $100 月度预算</button>:undefined}/><div className="p-5">{budget?<><div className="flex justify-between text-sm"><span>预算进度</span><span>${budget.spent_usd.toFixed(2)} / ${budget.limit_usd.toFixed(2)}</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full ${budget.exceeded?"bg-red-600":budget.warning?"bg-amber-500":"bg-emerald-500"}`} style={{width:`${Math.min(100,budget.spent_usd/budget.limit_usd*100)}%`}}/></div><div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><WalletCards className="h-4 w-4"/>告警 {Math.round(budget.warning_ratio*100)}% · {budget.hard_limit?"硬门禁已启用":"仅告警"}</div></>:<EmptyState title="尚未设置月度预算" description="预算可按 Workspace、团队或仓库配置。"/>}</div></Panel></div>
    <Panel className="mt-5"><PanelHeader title="模型调用账本" description={`${tokens.toLocaleString()} Token；不保存完整 Prompt 与回答`}/>{rows.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Provider / Model</th><th className="px-4 py-3">来源</th><th className="px-4 py-3">Token</th><th className="px-4 py-3">成本</th><th className="px-4 py-3">Trace</th><th className="px-4 py-3">时间</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-5 py-4 font-medium">{r.provider} / {r.model}</td><td className="px-4 py-4 text-slate-500">{r.source}</td><td className="px-4 py-4">{(r.input_tokens+r.output_tokens).toLocaleString()}</td><td className="px-4 py-4">${r.cost_usd.toFixed(4)}</td><td className="px-4 py-4 font-mono text-xs text-slate-500">{r.trace_id??"-"}</td><td className="px-4 py-4 text-slate-500">{new Date(r.occurred_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<EmptyState title="暂无调用明细" description="通过 GovernForge Model Gateway 调用后自动出现。"/>}</Panel>
  </AppLayout>
}
