"""Frozen initial AI Coding governance schema."""
from alembic import op
import sqlalchemy as sa

revision = "20260717_0001"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("workspaces", sa.Column("id", sa.String(36), primary_key=True), sa.Column("name", sa.String(128), nullable=False), sa.Column("slug", sa.String(64), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_workspaces_slug", "workspaces", ["slug"], unique=True)
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True), sa.Column("username", sa.String(64), nullable=False, unique=True), sa.Column("hashed_password", sa.String(256), nullable=False), sa.Column("tenant_id", sa.String(64), nullable=False), sa.Column("role", sa.String(32), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("refreshed_at", sa.DateTime()))
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.create_table("repositories", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("provider", sa.String(24), nullable=False), sa.Column("external_id", sa.String(128), nullable=False), sa.Column("full_name", sa.String(255), nullable=False), sa.Column("default_branch", sa.String(128), nullable=False), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("workspace_id", "provider", "external_id"))
    op.create_index("ix_repositories_workspace_id", "repositories", ["workspace_id"]); op.create_index("ix_repositories_full_name", "repositories", ["full_name"])
    op.create_table("pull_requests", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("repository_id", sa.String(36), sa.ForeignKey("repositories.id"), nullable=False), sa.Column("external_number", sa.Integer(), nullable=False), sa.Column("title", sa.String(512), nullable=False), sa.Column("author", sa.String(128), nullable=False), sa.Column("state", sa.String(24), nullable=False), sa.Column("head_sha", sa.String(64), nullable=False), sa.Column("additions", sa.Integer(), nullable=False), sa.Column("deletions", sa.Integer(), nullable=False), sa.Column("changed_files", sa.Integer(), nullable=False), sa.Column("source_confidence", sa.Float(), nullable=False), sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False), sa.Column("merged_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("repository_id", "external_number"))
    op.create_index("ix_pull_requests_workspace_id", "pull_requests", ["workspace_id"]); op.create_index("ix_pull_requests_repository_id", "pull_requests", ["repository_id"]); op.create_index("ix_pull_requests_head_sha", "pull_requests", ["head_sha"])
    op.create_table("ci_runs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("repository_id", sa.String(36), sa.ForeignKey("repositories.id"), nullable=False), sa.Column("pull_request_id", sa.String(36), sa.ForeignKey("pull_requests.id")), sa.Column("external_id", sa.String(128), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("conclusion", sa.String(32)), sa.Column("attempt", sa.Integer(), nullable=False), sa.Column("coverage", sa.Float()), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("repository_id", "external_id"))
    op.create_index("ix_ci_runs_workspace_id", "ci_runs", ["workspace_id"]); op.create_index("ix_ci_runs_pull_request_id", "ci_runs", ["pull_request_id"])
    op.create_table("ai_usage_events", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("repository_id", sa.String(36), sa.ForeignKey("repositories.id")), sa.Column("pull_request_id", sa.String(36), sa.ForeignKey("pull_requests.id")), sa.Column("external_id", sa.String(128), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("model", sa.String(128), nullable=False), sa.Column("input_tokens", sa.Integer(), nullable=False), sa.Column("output_tokens", sa.Integer(), nullable=False), sa.Column("cost_usd", sa.Float(), nullable=False), sa.Column("trace_id", sa.String(128)), sa.Column("source", sa.String(64), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("workspace_id", "external_id"))
    for name, cols in (("ix_ai_usage_events_workspace_id", ["workspace_id"]),("ix_ai_usage_events_repository_id", ["repository_id"]),("ix_ai_usage_events_pull_request_id", ["pull_request_id"]),("ix_ai_usage_events_trace_id", ["trace_id"])): op.create_index(name, "ai_usage_events", cols)
    op.create_table("webhook_deliveries", sa.Column("id", sa.String(36), primary_key=True), sa.Column("provider", sa.String(24), nullable=False), sa.Column("delivery_id", sa.String(128), nullable=False), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("provider", "delivery_id"))
    op.create_table("policy_evaluations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("pull_request_id", sa.String(36), sa.ForeignKey("pull_requests.id")), sa.Column("policy_version", sa.String(32), nullable=False), sa.Column("decision", sa.String(16), nullable=False), sa.Column("reasons", sa.JSON(), nullable=False), sa.Column("checks", sa.JSON(), nullable=False), sa.Column("evidence", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_policy_evaluations_workspace_id", "policy_evaluations", ["workspace_id"]); op.create_index("ix_policy_evaluations_pull_request_id", "policy_evaluations", ["pull_request_id"]); op.create_index("ix_policy_evaluations_decision", "policy_evaluations", ["decision"])
    op.create_table("approval_requests", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("pull_request_id", sa.String(36), sa.ForeignKey("pull_requests.id"), nullable=False), sa.Column("evaluation_id", sa.String(36), sa.ForeignKey("policy_evaluations.id"), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("required_role", sa.String(32), nullable=False), sa.Column("decided_by", sa.String(128)), sa.Column("reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True)))
    op.create_index("ix_approval_requests_workspace_id", "approval_requests", ["workspace_id"]); op.create_index("ix_approval_requests_pull_request_id", "approval_requests", ["pull_request_id"]); op.create_index("ix_approval_requests_status", "approval_requests", ["status"])
    op.create_table("governance_audit_events", sa.Column("id", sa.String(36), primary_key=True), sa.Column("workspace_id", sa.String(36), sa.ForeignKey("workspaces.id"), nullable=False), sa.Column("actor_id", sa.String(128), nullable=False), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("entity_type", sa.String(64), nullable=False), sa.Column("entity_id", sa.String(128), nullable=False), sa.Column("trace_id", sa.String(128)), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    for name, cols in (("ix_governance_audit_events_workspace_id",["workspace_id"]),("ix_governance_audit_events_event_type",["event_type"]),("ix_governance_audit_events_entity_id",["entity_id"]),("ix_governance_audit_events_trace_id",["trace_id"])): op.create_index(name, "governance_audit_events", cols)

def downgrade():
    for table in ("governance_audit_events", "approval_requests", "policy_evaluations", "webhook_deliveries", "ai_usage_events", "ci_runs", "pull_requests", "repositories", "users", "workspaces"): op.drop_table(table)
