"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ExternalLink, GitBranch, RefreshCw, Unplug } from "lucide-react";
import { AppLayout } from "@/components/layout/AppLayout";
import { EmptyState, Panel, PanelHeader, StatusBadge } from "@/components/ui/Console";
import { apiFetch } from "@/lib/api-client";

type Status={configured:boolean;app_id_configured:boolean;private_key_configured:boolean;webhook_secret_configured:boolean;checks_enabled:boolean;app_slug:string;install_url?:string;installations:{id:string;installation_id:string;account_login?:string;active:boolean;created_at:string}[];repositories:{id:string;full_name:string;installation_id?:string;active:boolean;html_url?:string}[]};
type Credential={id:string;name:string;provider:string;token_prefix:string;scopes:string[];active:boolean;expires_at:string;last_used_at?:string};

export default function Page(){
  const[data,setData]=useState<Status>(); const[credentials,setCredentials]=useState<Credential[]>([]); const[newToken,setNewToken]=useState("");
  const[installationId,setInstallationId]=useState(""); const[account,setAccount]=useState(""); const[busy,setBusy]=useState(false); const[error,setError]=useState(""); const[notice,setNotice]=useState("");
  async function load(){const[r,c]=await Promise.all([apiFetch<Status>("/api/integrations/github/status"),apiFetch<Credential[]>("/api/integrations/agent-credentials")]);if(r.error)setError(r.error.message);else setData(r.data!);if(c.data)setCredentials(c.data)}
  useEffect(()=>{void(async()=>{await load();const id=new URLSearchParams(location.search).get("installation_id");if(id){setInstallationId(id);setNotice("GitHub 已返回 Installation ID，请绑定到当前 Workspace。")}})()},[]);
  async function register(){if(!installationId)return;setBusy(true);const r=await apiFetch<any>("/api/integrations/github/installations",{method:"POST",body:JSON.stringify({installation_id:installationId,account_login:account||null})});if(r.error)setError(r.error.message);else{setNotice("Installation 已绑定，可以同步授权仓库。");setInstallationId("");await load()}setBusy(false)}
  async function sync(id:string){setBusy(true);const r=await apiFetch<any>(`/api/integrations/github/installations/${id}/sync`,{method:"POST",body:"{}"});if(r.error)setError(r.error.message);else{setNotice(`已同步 ${r.data.repositories} 个仓库`);await load()}setBusy(false)}
  async function disconnect(id:string){if(!confirm("断开这个 GitHub Installation？已同步仓库将停止治理。"))return;const r=await apiFetch(`/api/integrations/github/installations/${id}`,{method:"DELETE"});if(r.error)setError(r.error.message);else await load()}
  async function issueAgentKey(){const r=await apiFetch<any>("/api/integrations/agent-credentials",{method:"POST",body:JSON.stringify({name:`coding-agent-${Date.now()}`,provider:"coding-agent",expires_in_days:30,scopes:["agent:write"]})});if(r.error)setError(r.error.message);else{setNewToken(r.data.token);setNotice("服务凭据只显示一次，请立即保存到本机或企业密钥系统。");await load()}}
  async function revokeAgentKey(id:string){if(!confirm("撤销此 Agent 服务凭据？对应 Hook 将立即停止上报。"))return;const r=await apiFetch(`/api/integrations/agent-credentials/${id}`,{method:"DELETE"});if(r.error)setError(r.error.message);else await load()}
  return <AppLayout title="连接器" subtitle="接入 GitHub 与 Coding Agent；模型供应商统一在“模型网关与成本”管理。">
    {error&&<div className="mb-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    {newToken&&<div className="mb-5 rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="text-sm font-semibold text-amber-900">一次性 Agent Token</div><code className="mt-2 block break-all rounded bg-white p-3 text-xs text-slate-800">{newToken}</code><div className="mt-2 flex gap-3"><button onClick={()=>navigator.clipboard.writeText(newToken)} className="text-xs font-medium text-amber-800">复制</button><button onClick={()=>setNewToken("")} className="text-xs text-slate-500">已保存，关闭</button></div></div>}
    <div className="grid gap-5 xl:grid-cols-[1.2fr_1fr]"><Panel><PanelHeader title="GitHub App" description="Installation 授权仓库，接收 PR/CI 并回写策略 Check" action={<StatusBadge value={data?.configured?"active":"pending"}/>}/><div className="p-5"><div className="grid gap-3 sm:grid-cols-2">{[["App ID",data?.app_id_configured],["Private Key",data?.private_key_configured],["Webhook Secret",data?.webhook_secret_configured],["Checks 回写",data?.checks_enabled]].map(([label,ok])=><div key={String(label)} className="flex items-center justify-between rounded-lg border border-slate-200 p-3 text-sm"><span className="text-slate-600">{label as string}</span>{ok?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<span className="text-xs text-amber-600">待配置</span>}</div>)}</div><div className="mt-5 rounded-lg bg-slate-50 p-4"><div className="text-sm font-medium">安装与同步</div><p className="mt-2 text-xs leading-6 text-slate-500">完成 GitHub App 安装后，将 Installation ID 绑定到 Workspace。Webhook 会按 head SHA 自动取证和评估。</p>{data?.install_url?<a href={data.install_url} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2 text-sm text-white">安装 GitHub App<ExternalLink className="h-4 w-4"/></a>:<div className="mt-3 text-xs text-amber-700">请先配置 GITHUB_APP_SLUG。</div>}</div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input value={installationId} onChange={e=>setInstallationId(e.target.value)} placeholder="Installation ID" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"/><input value={account} onChange={e=>setAccount(e.target.value)} placeholder="GitHub 组织/账号" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"/><button onClick={register} disabled={!installationId||busy} className="rounded-lg bg-blue-600 px-4 py-2 text-sm text-white disabled:opacity-40">绑定</button></div></div></Panel>
      <Panel><PanelHeader title="已绑定 Installation" description="每个 Installation 只能归属一个 Workspace"/><div className="divide-y divide-slate-100">{data?.installations.map(item=><div key={item.id} className="p-5"><div className="flex items-start justify-between"><div className="flex gap-3"><GitBranch className="h-5 w-5"/><div><div className="font-medium">{item.account_login||"GitHub Installation"}</div><div className="mt-1 text-xs text-slate-500">ID {item.installation_id}</div></div></div><StatusBadge value={item.active?"active":"blocked"}/></div>{item.active&&<div className="mt-4 flex gap-2"><button onClick={()=>sync(item.installation_id)} disabled={busy||!data.configured} className="inline-flex items-center gap-1.5 rounded border px-3 py-1.5 text-xs disabled:opacity-40"><RefreshCw className="h-3.5 w-3.5"/>同步仓库</button><button onClick={()=>disconnect(item.installation_id)} className="inline-flex items-center gap-1.5 rounded border border-red-200 px-3 py-1.5 text-xs text-red-600"><Unplug className="h-3.5 w-3.5"/>断开</button></div>}</div>)}{!data?.installations.length&&<EmptyState title="尚未绑定 GitHub" description="完成 App 安装后，Installation 会显示在这里。"/>}</div></Panel></div>
    <Panel className="mt-5"><PanelHeader title="Coding Agent 服务身份" description="Codex 与 Claude Code Hook 使用可撤销机器凭据，不复用个人登录 Token" action={<button onClick={issueAgentKey} className="rounded-lg bg-slate-950 px-4 py-2 text-sm text-white">签发 30 天凭据</button>}/><div className="divide-y divide-slate-100">{credentials.map(item=><div key={item.id} className="flex items-center justify-between gap-4 p-5"><div><div className="text-sm font-medium">{item.name}</div><div className="mt-1 font-mono text-xs text-slate-400">{item.token_prefix}… · {item.scopes.join(", ")}</div><div className="mt-1 text-xs text-slate-500">到期 {new Date(item.expires_at).toLocaleString()} · 最近使用 {item.last_used_at?new Date(item.last_used_at).toLocaleString():"从未"}</div></div><div className="flex items-center gap-3"><StatusBadge value={item.active?"active":"blocked"}/>{item.active&&<button onClick={()=>revokeAgentKey(item.id)} className="text-xs text-red-600">撤销</button>}</div></div>)}{!credentials.length&&<EmptyState title="尚未签发 Agent 凭据" description="签发后设置 GOVERNFORGE_AGENT_TOKEN，再运行 Hook 安装命令。"/>}</div></Panel>
  </AppLayout>
}
